// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzHSIo_WDGEYOsxxVl5BiIlbjeoKKxvbU',
    appId: '1:940864314483:web:5e8872ad6fde8595df5e06',
    messagingSenderId: '940864314483',
    projectId: 'gaspromneft-1fdc6',
    authDomain: 'gaspromneft-1fdc6.firebaseapp.com',
    storageBucket: 'gaspromneft-1fdc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlYF5-H4pEN-Vri2mfzj8X_l7QHzXbbnY',
    appId: '1:940864314483:android:6f63ecfb59d76664df5e06',
    messagingSenderId: '940864314483',
    projectId: 'gaspromneft-1fdc6',
    storageBucket: 'gaspromneft-1fdc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkVBHJUsYrYqTGWZMKqe0_8coyBVs53n8',
    appId: '1:940864314483:ios:fc503756e4ef24afdf5e06',
    messagingSenderId: '940864314483',
    projectId: 'gaspromneft-1fdc6',
    storageBucket: 'gaspromneft-1fdc6.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkVBHJUsYrYqTGWZMKqe0_8coyBVs53n8',
    appId: '1:940864314483:ios:f3738c6a2ac52162df5e06',
    messagingSenderId: '940864314483',
    projectId: 'gaspromneft-1fdc6',
    storageBucket: 'gaspromneft-1fdc6.appspot.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
