// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANve_Aon8Z1AUv16iUaPecA9Y7bfFOT5Y',
    appId: '1:371198022746:web:3756c7c04275c2a06af463',
    messagingSenderId: '371198022746',
    projectId: 'cloudchat-5583c',
    authDomain: 'cloudchat-5583c.firebaseapp.com',
    databaseURL: 'https://cloudchat-5583c.firebaseio.com',
    storageBucket: 'cloudchat-5583c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxps7GuoiqYNUOSfntEXZde7Bov3x3YaM',
    appId: '1:371198022746:android:b83607d7bff4c7756af463',
    messagingSenderId: '371198022746',
    projectId: 'cloudchat-5583c',
    databaseURL: 'https://cloudchat-5583c.firebaseio.com',
    storageBucket: 'cloudchat-5583c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2HxKZ0QZE5G4v1wl-nV5pN3fO680qjM',
    appId: '1:371198022746:ios:334c0b51a485b0bb6af463',
    messagingSenderId: '371198022746',
    projectId: 'cloudchat-5583c',
    databaseURL: 'https://cloudchat-5583c.firebaseio.com',
    storageBucket: 'cloudchat-5583c.appspot.com',
    androidClientId: '371198022746-n1cr5c7lssot0ul4dc5liof6dnn9aeu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2HxKZ0QZE5G4v1wl-nV5pN3fO680qjM',
    appId: '1:371198022746:ios:b71a031e95725e306af463',
    messagingSenderId: '371198022746',
    projectId: 'cloudchat-5583c',
    databaseURL: 'https://cloudchat-5583c.firebaseio.com',
    storageBucket: 'cloudchat-5583c.appspot.com',
    androidClientId: '371198022746-n1cr5c7lssot0ul4dc5liof6dnn9aeu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
